addons:
  apt:
    sources:
      - boost-latest
    packages:
      - gcc
      - g++
      - doxygen
      - libboost-all-dev

script:
  - mkdir build.release
  - cd build.release
  - cmake -DCMAKE_BUILD_TYPE=Release -DKART_BUILD_EXAMPLES=TRUE ..
  - make -j

